blank_issues_enabled: false
contact_links:
  - name: NestJS Discord
    url: https://discord.gg/nestjs
    about: Join the official NestJS Discord community for discussions
  - name: NestJS Documentation
    url: https://docs.nestjs.com
    about: Check the official NestJS documentation

